# Generated by Django 2.0 on 2018-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180315_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
