# Generated by Django 2.0.3 on 2018-03-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_post', to='core.Noticia'),
            preserve_default=False,
        ),
    ]
