# Generated by Django 2.0.3 on 2018-03-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='capa_noticia',
            field=models.FileField(default=1, upload_to='media/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
