# Generated by Django 2.0.3 on 2018-03-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180321_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='consideração_final',
            new_name='consideracao_final',
        ),
    ]
