# Generated by Django 2.0.3 on 2018-03-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180321_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='capa_noticia',
            field=models.ImageField(default='imagens/perfil.jpg', upload_to='media/%Y/%m/%d/'),
        ),
    ]
