# Generated by Django 2.0.3 on 2018-03-21 18:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180321_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2018-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='capa_noticia',
            field=models.ImageField(upload_to=core.models.get_image_path_noticia),
        ),
    ]
