# Generated by Django 2.0.3 on 2018-03-21 19:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180321_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='img_principal',
            field=models.ImageField(upload_to=core.models.get_image_path_evento),
        ),
    ]
