# Generated by Django 2.0.3 on 2018-03-21 19:35

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_perfil_perfil_image'),
        ('core', '0013_auto_20180321_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=140)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_eventos', to='perfis.Perfil')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_evento', to='core.Evento')),
            ],
        ),
        migrations.AlterField(
            model_name='imagem_evento',
            name='imagem',
            field=models.ImageField(upload_to=core.models.get_image_path_evento),
        ),
        migrations.AlterField(
            model_name='imagens_noticia',
            name='imagem',
            field=models.ImageField(upload_to=core.models.get_image_path_noticia),
        ),
    ]
