# Generated by Django 2.0.3 on 2018-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180321_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_evento',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
