# Generated by Django 2.0.3 on 2018-03-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_evento_hora_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_evento',
            field=models.CharField(max_length=8),
        ),
    ]
