# Generated by Django 2.0 on 2018-03-15 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import perfis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens_noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='noticias/%Y/%m/%d')),
                ('legenda', models.CharField(max_length=30)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('primeiro_paragrafo', models.CharField(max_length=1000)),
                ('segundo_paragrafo', models.CharField(max_length=1000, null=True)),
                ('consideração_final', models.CharField(max_length=100, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=11)),
                ('faixa', enumfields.fields.EnumField(default=10, enum=perfis.models.Faixa, max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aniversario', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='imagens_noticia',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia', to='perfis.Noticia'),
        ),
    ]
