# Generated by Django 2.0 on 2018-03-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagens_noticia',
            name='noticia',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Imagens_noticia',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
