# Generated by Django 2.0 on 2018-03-16 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import perfis.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfis', '0002_auto_20180315_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=11)),
                ('faixa', enumfields.fields.EnumField(default=5, enum=perfis.models.Faixa, max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aniversario', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
