# Generated by Django 2.0.3 on 2018-03-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20180317_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='perfil_image',
            field=models.ImageField(default='imagens/perfil.jpg', upload_to='perfis/'),
        ),
    ]
