# Generated by Django 2.0.3 on 2018-03-22 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_auto_20180322_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='permissao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='perfis.Permissao_perfil'),
            preserve_default=False,
        ),
    ]
