# Generated by Django 2.0.3 on 2018-03-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_perfil_permissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='perfil_image',
        ),
    ]
